using FundLedger.Domain.Organizations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FundLedger.Infrastructure.Persistence.Configurations;

internal sealed class OrganizationConfiguration : IEntityTypeConfiguration<Organization>
{
    public void Configure(EntityTypeBuilder<Organization> builder)
    {
        builder.ToTable("organizations");
        builder.HasKey(o => o.Id);
        builder.Property(o => o.Id).ValueGeneratedNever();           // UUIDv7 generated by the app
        builder.Property(o => o.Name).HasMaxLength(150);
        builder.Property(o => o.ShortCode).HasMaxLength(10);
        builder.HasIndex(o => o.ShortCode).IsUnique();
        builder.Property(o => o.ContactMobile).HasMaxLength(15);
        builder.Property(o => o.ContactEmail).HasColumnType("citext");
        builder.Property(o => o.RegistrationNumber).HasMaxLength(60);
        builder.Property(o => o.CurrencyCode).HasColumnType("char(3)");
        builder.Property(o => o.Timezone).HasMaxLength(64);
        builder.Property(o => o.DateFormat).HasMaxLength(20);
        builder.Property(o => o.CreatedAt).HasDefaultValueSql("now()");
        builder.Property(o => o.UpdatedAt).HasDefaultValueSql("now()");
    }
}
