-- =============================================================================
-- FundLedger — PostgreSQL schema (V1 baseline)
-- Source of truth for docs/04-Backend-Schema.md. EF Core migrations must
-- reproduce this DDL; any divergence is a bug in one or the other.
--
-- Target: PostgreSQL 16+
-- Conventions:
--   * snake_case identifiers; EF Core maps via UseSnakeCaseNamingConvention()
--   * UUID v7 primary keys generated by the application (time-ordered)
--   * money = numeric(18,2), always > 0; direction is carried by txn type
--   * every tenant table carries organization_id and is protected by RLS
--   * timestamps are timestamptz (UTC); business date/time are local to org tz
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;   -- fuzzy search on purpose/party names

-- -----------------------------------------------------------------------------
-- Database roles (run once per environment by an operator, not by migrations)
--   fundledger_owner    : owns objects, runs migrations (CI only)
--   fundledger_app      : runtime API role — NOT owner, NO BYPASSRLS
--   fundledger_readonly : reporting / support read access (still subject to RLS)
--   fundledger_auth_definer : NOLOGIN, BYPASSRLS; owns only pre-auth lookup functions
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fundledger_app') THEN
    CREATE ROLE fundledger_app NOLOGIN NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fundledger_readonly') THEN
    CREATE ROLE fundledger_readonly NOLOGIN NOBYPASSRLS;
  END IF;
  -- Owns ONLY the narrow pre-authentication lookup functions (section 13).
  -- Never granted to a login role. Requires superuser to create.
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fundledger_auth_definer') THEN
    CREATE ROLE fundledger_auth_definer NOLOGIN BYPASSRLS;
  END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS fl;
SET search_path = fl, public;

-- -----------------------------------------------------------------------------
-- Enumerations
-- -----------------------------------------------------------------------------
CREATE TYPE fl.user_role          AS ENUM ('ADMIN', 'MEMBER');
CREATE TYPE fl.user_status        AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE fl.fund_status        AS ENUM ('DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED');
CREATE TYPE fl.account_kind       AS ENUM ('CASH', 'BANK', 'UPI', 'WALLET', 'OTHER');
CREATE TYPE fl.category_direction AS ENUM ('MONEY_IN', 'MONEY_OUT');
CREATE TYPE fl.txn_type           AS ENUM ('DEPOSIT', 'EXPENSE', 'TRANSFER', 'ADJUSTMENT');
CREATE TYPE fl.adj_direction      AS ENUM ('INCREASE', 'DECREASE');
CREATE TYPE fl.txn_status         AS ENUM ('ACTIVE', 'CANCELLED');
CREATE TYPE fl.auth_method        AS ENUM ('PIN');          -- V1 is PIN-only (ADR-0002); add values later via ALTER TYPE
CREATE TYPE fl.export_status      AS ENUM ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED');

-- -----------------------------------------------------------------------------
-- Session context helpers (set by the API per DB connection/transaction)
--   app.org_id   uuid  — tenant of the authenticated user
--   app.user_id  uuid  — authenticated user
--   app.is_admin bool  — role shortcut for policies
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fl.current_org_id() RETURNS uuid
  LANGUAGE sql STABLE AS
$$ SELECT nullif(current_setting('app.org_id', true), '')::uuid $$;

CREATE OR REPLACE FUNCTION fl.current_user_id() RETURNS uuid
  LANGUAGE sql STABLE AS
$$ SELECT nullif(current_setting('app.user_id', true), '')::uuid $$;

CREATE OR REPLACE FUNCTION fl.current_is_admin() RETURNS boolean
  LANGUAGE sql STABLE AS
$$ SELECT coalesce(nullif(current_setting('app.is_admin', true), '')::boolean, false) $$;

-- Generic updated_at maintenance
CREATE OR REPLACE FUNCTION fl.touch_updated_at() RETURNS trigger
  LANGUAGE plpgsql AS
$$ BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

-- =============================================================================
-- 1. Organizations & settings
-- =============================================================================
CREATE TABLE fl.organizations (
  id                 uuid PRIMARY KEY,
  name               varchar(150) NOT NULL,
  short_code         varchar(10)  NOT NULL UNIQUE,         -- used in txn numbers
  contact_mobile     varchar(15),
  contact_email      citext,
  address            text,
  registration_number varchar(60),                          -- trust/society reg. no., printed on receipts
  currency_code      char(3)      NOT NULL DEFAULT 'INR',
  timezone           varchar(64)  NOT NULL DEFAULT 'Asia/Kolkata',
  date_format        varchar(20)  NOT NULL DEFAULT 'dd-MMM-yyyy',
  max_active_users   smallint     NOT NULL DEFAULT 50 CHECK (max_active_users BETWEEN 1 AND 50),
  is_active          boolean      NOT NULL DEFAULT true,
  created_at         timestamptz  NOT NULL DEFAULT now(),
  updated_at         timestamptz  NOT NULL DEFAULT now()
);

-- Key/value settings with typed JSON values (validated in the API).
-- Known keys (see docs/04-Backend-Schema.md §5):
--   auth.pin_max_failures, auth.pin_lockout_minutes, auth.session_idle_minutes,
--   auth.session_absolute_days, txn.edit_window_minutes, txn.backdate_days_member,
--   txn.max_amount, txn.number_period, txn.block_negative_account,
--   receipt.enabled, receipt.footer_text, receipt.show_recorded_by,
--   attachments.max_mb, attachments.allowed_types, offline.enabled, offline.max_queue_age_hours
CREATE TABLE fl.settings (
  organization_id    uuid        NOT NULL REFERENCES fl.organizations(id),
  key                varchar(80) NOT NULL,
  value              jsonb       NOT NULL,
  updated_by         uuid,
  updated_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, key)
);

-- =============================================================================
-- 2. Users, sessions, login attempts
-- =============================================================================
CREATE TABLE fl.users (
  id                 uuid PRIMARY KEY,
  organization_id    uuid         NOT NULL REFERENCES fl.organizations(id),
  full_name          varchar(120) NOT NULL,
  mobile_e164        varchar(15)  NOT NULL CHECK (mobile_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  email              citext,
  role               fl.user_role   NOT NULL DEFAULT 'MEMBER',
  status             fl.user_status NOT NULL DEFAULT 'ACTIVE',
  pin_hash           text,                                   -- PBKDF2 via ASP.NET Identity PasswordHasher; null until Admin sets a temporary PIN
  pin_set_at         timestamptz,                            -- lockout window restarts on PIN set/reset
  pin_must_change    boolean      NOT NULL DEFAULT true,     -- true after Admin set/reset; user must choose own PIN
  last_login_at      timestamptz,
  deactivated_at     timestamptz,
  deactivated_by     uuid REFERENCES fl.users(id),
  created_by         uuid REFERENCES fl.users(id),           -- null only for bootstrap admin
  created_at         timestamptz  NOT NULL DEFAULT now(),
  updated_by         uuid REFERENCES fl.users(id),
  updated_at         timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uq_users_org_mobile UNIQUE (organization_id, mobile_e164)
);
CREATE INDEX ix_users_org_status ON fl.users (organization_id, status);

-- BR-001: hard backstop for the 50-active-user limit. The API checks first and
-- returns a friendly error; this trigger guarantees it under concurrency.
CREATE OR REPLACE FUNCTION fl.enforce_active_user_limit() RETURNS trigger
  LANGUAGE plpgsql AS
$$
DECLARE
  v_limit  smallint;
  v_active integer;
BEGIN
  IF NEW.status = 'ACTIVE' AND (TG_OP = 'INSERT' OR OLD.status <> 'ACTIVE') THEN
    -- serialize concurrent activations within one organization
    PERFORM pg_advisory_xact_lock(hashtext('user_limit:' || NEW.organization_id::text));
    SELECT max_active_users INTO v_limit FROM fl.organizations WHERE id = NEW.organization_id;
    SELECT count(*) INTO v_active FROM fl.users
      WHERE organization_id = NEW.organization_id AND status = 'ACTIVE' AND id <> NEW.id;
    IF v_active >= v_limit THEN
      RAISE EXCEPTION 'ACTIVE_USER_LIMIT_REACHED' USING ERRCODE = 'P0001',
        DETAIL = format('Organization %s already has %s active users (limit %s)',
                        NEW.organization_id, v_active, v_limit);
    END IF;
  END IF;
  RETURN NEW;
END
$$;
CREATE TRIGGER trg_users_active_limit
  BEFORE INSERT OR UPDATE OF status ON fl.users
  FOR EACH ROW EXECUTE FUNCTION fl.enforce_active_user_limit();
CREATE TRIGGER trg_users_touch BEFORE UPDATE ON fl.users
  FOR EACH ROW EXECUTE FUNCTION fl.touch_updated_at();

-- PIN login attempts (ADR-0002). Recorded for EVERY attempt, including unknown
-- numbers, so lockout is computed per mobile number without revealing whether
-- the number is registered. Lockout = >= auth.pin_max_failures failures for the
-- mobile within auth.pin_lockout_minutes, counted after the user's pin_set_at.
-- No PINs are ever stored here. Pre-auth table: no tenant, no RLS.
CREATE TABLE fl.login_attempts (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  mobile_e164        varchar(15) NOT NULL,
  user_id            uuid REFERENCES fl.users(id),           -- null when number unknown
  succeeded          boolean     NOT NULL,
  failure_code       varchar(30),                            -- BAD_PIN, LOCKED, INACTIVE, UNKNOWN (internal only)
  ip_address         inet,
  user_agent         varchar(300),
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_login_attempts_mobile ON fl.login_attempts (mobile_e164, created_at DESC);
CREATE INDEX ix_login_attempts_ip     ON fl.login_attempts (ip_address, created_at DESC);

-- Server-side sessions: refresh tokens are rotated on every use and stored
-- hashed. Reuse of a rotated token revokes the whole family (theft detection).
CREATE TABLE fl.user_sessions (
  id                 uuid PRIMARY KEY,
  organization_id    uuid        NOT NULL REFERENCES fl.organizations(id),
  user_id            uuid        NOT NULL REFERENCES fl.users(id),
  family_id          uuid        NOT NULL,
  refresh_token_hash bytea       NOT NULL UNIQUE,            -- SHA-256 of opaque token
  replaced_by        uuid REFERENCES fl.user_sessions(id),
  auth_method        fl.auth_method NOT NULL,
  device_label       varchar(120),
  user_agent         text,
  ip_address         inet,
  created_at         timestamptz NOT NULL DEFAULT now(),
  last_used_at       timestamptz,
  expires_at         timestamptz NOT NULL,
  revoked_at         timestamptz,
  revoke_reason      varchar(40)
);
CREATE INDEX ix_sessions_user_active ON fl.user_sessions (user_id) WHERE revoked_at IS NULL;
CREATE INDEX ix_sessions_family      ON fl.user_sessions (family_id);

-- =============================================================================
-- 3. Lookups: fund types, account types, payment modes
-- =============================================================================
CREATE TABLE fl.fund_types (
  id                 uuid PRIMARY KEY,
  organization_id    uuid        NOT NULL REFERENCES fl.organizations(id),
  name               varchar(60) NOT NULL,                   -- Event, Charity, Masjid, Medical, ...
  is_active          boolean     NOT NULL DEFAULT true,
  sort_order         smallint    NOT NULL DEFAULT 0,
  CONSTRAINT uq_fund_types_name UNIQUE (organization_id, name)
);

CREATE TABLE fl.payment_modes (
  id                 uuid PRIMARY KEY,
  organization_id    uuid        NOT NULL REFERENCES fl.organizations(id),
  name               varchar(40) NOT NULL,                   -- Cash, UPI, Bank Transfer, Cheque, Card, Other
  requires_reference boolean     NOT NULL DEFAULT false,     -- e.g. UPI txn id, cheque no.
  is_active          boolean     NOT NULL DEFAULT true,
  sort_order         smallint    NOT NULL DEFAULT 0,
  CONSTRAINT uq_payment_modes_name UNIQUE (organization_id, name)
);

-- =============================================================================
-- 4. Funds / activities and access
-- =============================================================================
CREATE TABLE fl.funds (
  id                 uuid PRIMARY KEY,
  organization_id    uuid         NOT NULL REFERENCES fl.organizations(id),
  fund_type_id       uuid         NOT NULL REFERENCES fl.fund_types(id),
  code               varchar(10)  NOT NULL,                  -- e.g. IJT26; used in txn numbers
  name               varchar(120) NOT NULL,
  description        text,
  start_date         date,
  end_date           date,
  status             fl.fund_status NOT NULL DEFAULT 'DRAFT',
  closed_at          timestamptz,
  closed_by          uuid REFERENCES fl.users(id),
  created_by         uuid         NOT NULL REFERENCES fl.users(id),
  created_at         timestamptz  NOT NULL DEFAULT now(),
  updated_by         uuid REFERENCES fl.users(id),
  updated_at         timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uq_funds_code UNIQUE (organization_id, code),
  CONSTRAINT uq_funds_name UNIQUE (organization_id, name),
  CONSTRAINT ck_funds_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);
CREATE INDEX ix_funds_org_status ON fl.funds (organization_id, status);
CREATE TRIGGER trg_funds_touch BEFORE UPDATE ON fl.funds
  FOR EACH ROW EXECUTE FUNCTION fl.touch_updated_at();

-- Per-user, per-fund permissions. Admins implicitly have everything on every
-- fund and do not need rows here.
CREATE TABLE fl.user_fund_access (
  organization_id    uuid        NOT NULL REFERENCES fl.organizations(id),
  user_id            uuid        NOT NULL REFERENCES fl.users(id),
  fund_id            uuid        NOT NULL REFERENCES fl.funds(id),
  can_money_in       boolean     NOT NULL DEFAULT true,
  can_money_out      boolean     NOT NULL DEFAULT true,
  can_transfer       boolean     NOT NULL DEFAULT false,
  can_view_reports   boolean     NOT NULL DEFAULT true,
  can_export         boolean     NOT NULL DEFAULT false,
  can_view_all_txns  boolean     NOT NULL DEFAULT true,      -- false = only own transactions
  granted_by         uuid        NOT NULL REFERENCES fl.users(id),
  granted_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, fund_id)
);
CREATE INDEX ix_ufa_fund ON fl.user_fund_access (fund_id);

-- =============================================================================
-- 5. Accounts (money-holding places) and opening balances
-- Accounts are organization-level so one physical cash box / bank account can
-- hold money for several funds. Balances are always computed per (fund, account).
-- =============================================================================
CREATE TABLE fl.accounts (
  id                 uuid PRIMARY KEY,
  organization_id    uuid         NOT NULL REFERENCES fl.organizations(id),
  name               varchar(80)  NOT NULL,                  -- Main Cash, Bank - SBI, Cash Counter 1
  kind               fl.account_kind NOT NULL,
  bank_name          varchar(80),
  account_number_last4 char(4),                              -- never store full account numbers
  is_active          boolean      NOT NULL DEFAULT true,
  sort_order         smallint     NOT NULL DEFAULT 0,
  created_by         uuid         NOT NULL REFERENCES fl.users(id),
  created_at         timestamptz  NOT NULL DEFAULT now(),
  updated_by         uuid REFERENCES fl.users(id),
  updated_at         timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uq_accounts_name UNIQUE (organization_id, name)
);
CREATE TRIGGER trg_accounts_touch BEFORE UPDATE ON fl.accounts
  FOR EACH ROW EXECUTE FUNCTION fl.touch_updated_at();

-- Fund opening balance = SUM of its rows here (BR-015: admin-only, audited).
-- amount may be 0; negative opening balances are not allowed.
CREATE TABLE fl.opening_balances (
  organization_id    uuid          NOT NULL REFERENCES fl.organizations(id),
  fund_id            uuid          NOT NULL REFERENCES fl.funds(id),
  account_id         uuid          NOT NULL REFERENCES fl.accounts(id),
  amount             numeric(18,2) NOT NULL CHECK (amount >= 0),
  as_of_date         date          NOT NULL,
  set_by             uuid          NOT NULL REFERENCES fl.users(id),
  set_at             timestamptz   NOT NULL DEFAULT now(),
  PRIMARY KEY (fund_id, account_id)
);

-- =============================================================================
-- 6. Categories
-- =============================================================================
CREATE TABLE fl.categories (
  id                 uuid PRIMARY KEY,
  organization_id    uuid        NOT NULL REFERENCES fl.organizations(id),
  fund_id            uuid REFERENCES fl.funds(id),           -- null = available to all funds
  direction          fl.category_direction NOT NULL,
  name               varchar(60) NOT NULL,
  icon               varchar(40),                            -- lucide icon name for UI
  is_active          boolean     NOT NULL DEFAULT true,
  sort_order         smallint    NOT NULL DEFAULT 0,
  created_by         uuid        NOT NULL REFERENCES fl.users(id),
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_by         uuid REFERENCES fl.users(id),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
-- name unique per (org, direction, scope)
CREATE UNIQUE INDEX uq_categories_name
  ON fl.categories (organization_id, direction, coalesce(fund_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(name));
CREATE TRIGGER trg_categories_touch BEFORE UPDATE ON fl.categories
  FOR EACH ROW EXECUTE FUNCTION fl.touch_updated_at();

-- =============================================================================
-- 7. Transaction numbering
-- Gap-free per (fund, period) sequence. Allocated inside the same DB
-- transaction as the insert using INSERT ... ON CONFLICT DO UPDATE ... RETURNING
-- (row lock serializes concurrent allocations; rollback releases the number).
-- =============================================================================
CREATE TABLE fl.txn_number_sequences (
  organization_id    uuid     NOT NULL REFERENCES fl.organizations(id),
  fund_id            uuid     NOT NULL REFERENCES fl.funds(id),
  period_key         varchar(9) NOT NULL,                    -- e.g. '2026-27' (Indian FY) or '2026'
  last_value         integer  NOT NULL DEFAULT 0,
  PRIMARY KEY (fund_id, period_key)
);

-- =============================================================================
-- 8. Transactions — the single generic ledger table (PRD §7, §24.2)
-- One row per financial event. TRANSFER rows use from/to accounts and do not
-- use account_id/category_id. Rows are never deleted (BR-012).
-- =============================================================================
CREATE TABLE fl.transactions (
  id                    uuid PRIMARY KEY,
  organization_id       uuid          NOT NULL REFERENCES fl.organizations(id),
  fund_id               uuid          NOT NULL REFERENCES fl.funds(id),
  txn_number            varchar(30)   NOT NULL,              -- e.g. IJT26-2026-27-000123
  txn_type              fl.txn_type   NOT NULL,
  amount                numeric(18,2) NOT NULL CHECK (amount > 0),          -- BR-005
  txn_date              date          NOT NULL,                              -- BR-006 (org local)
  txn_time              time(0)       NOT NULL,
  category_id           uuid REFERENCES fl.categories(id),
  account_id            uuid REFERENCES fl.accounts(id),
  from_account_id       uuid REFERENCES fl.accounts(id),
  to_account_id         uuid REFERENCES fl.accounts(id),
  adjustment_direction  fl.adj_direction,
  payment_mode_id       uuid REFERENCES fl.payment_modes(id),
  received_from         varchar(120),
  paid_to               varchar(120),
  purpose               varchar(300),
  reference_number      varchar(80),
  remarks               text,
  status                fl.txn_status NOT NULL DEFAULT 'ACTIVE',
  client_txn_id         uuid,                                -- BR-018 offline idempotency key
  source                varchar(10)   NOT NULL DEFAULT 'ONLINE' CHECK (source IN ('ONLINE','OFFLINE','IMPORT')),
  client_created_at     timestamptz,                         -- device clock when queued offline
  revision              integer       NOT NULL DEFAULT 1,    -- bumps on every edit
  created_by            uuid          NOT NULL REFERENCES fl.users(id),      -- BR-007
  created_at            timestamptz   NOT NULL DEFAULT now(),
  updated_by            uuid REFERENCES fl.users(id),
  updated_at            timestamptz,
  cancelled_by          uuid REFERENCES fl.users(id),
  cancelled_at          timestamptz,
  cancellation_reason   varchar(300),

  CONSTRAINT uq_txn_number UNIQUE (organization_id, txn_number),
  -- BR-019: duplicate sync is impossible at the DB level
  CONSTRAINT uq_txn_client_id UNIQUE (organization_id, client_txn_id),

  -- Shape rules per type (BR-008, BR-009, BR-010)
  CONSTRAINT ck_txn_deposit_shape CHECK (
    txn_type <> 'DEPOSIT' OR (
      account_id IS NOT NULL AND category_id IS NOT NULL AND payment_mode_id IS NOT NULL
      AND purpose IS NOT NULL AND from_account_id IS NULL AND to_account_id IS NULL
      AND adjustment_direction IS NULL)),
  CONSTRAINT ck_txn_expense_shape CHECK (
    txn_type <> 'EXPENSE' OR (
      account_id IS NOT NULL AND category_id IS NOT NULL AND payment_mode_id IS NOT NULL
      AND purpose IS NOT NULL AND length(trim(purpose)) > 0
      AND from_account_id IS NULL AND to_account_id IS NULL AND adjustment_direction IS NULL)),
  CONSTRAINT ck_txn_transfer_shape CHECK (
    txn_type <> 'TRANSFER' OR (
      from_account_id IS NOT NULL AND to_account_id IS NOT NULL
      AND from_account_id <> to_account_id
      AND account_id IS NULL AND category_id IS NULL AND adjustment_direction IS NULL)),
  CONSTRAINT ck_txn_adjustment_shape CHECK (
    txn_type <> 'ADJUSTMENT' OR (
      account_id IS NOT NULL AND adjustment_direction IS NOT NULL
      AND purpose IS NOT NULL AND length(trim(purpose)) > 0          -- reason mandatory
      AND from_account_id IS NULL AND to_account_id IS NULL)),
  -- BR-013: cancellation requires reason + actor + time
  CONSTRAINT ck_txn_cancel_shape CHECK (
    (status = 'ACTIVE' AND cancelled_at IS NULL AND cancelled_by IS NULL AND cancellation_reason IS NULL)
    OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND cancelled_by IS NOT NULL
        AND cancellation_reason IS NOT NULL AND length(trim(cancellation_reason)) > 0))
);

CREATE INDEX ix_txn_fund_date      ON fl.transactions (fund_id, txn_date DESC, txn_time DESC);
CREATE INDEX ix_txn_fund_status    ON fl.transactions (fund_id, status) INCLUDE (txn_type, amount);
CREATE INDEX ix_txn_account        ON fl.transactions (account_id) WHERE account_id IS NOT NULL;
CREATE INDEX ix_txn_from_account   ON fl.transactions (from_account_id) WHERE from_account_id IS NOT NULL;
CREATE INDEX ix_txn_to_account     ON fl.transactions (to_account_id) WHERE to_account_id IS NOT NULL;
CREATE INDEX ix_txn_category       ON fl.transactions (category_id) WHERE category_id IS NOT NULL;
CREATE INDEX ix_txn_created_by     ON fl.transactions (created_by, created_at DESC);
CREATE INDEX ix_txn_ref            ON fl.transactions (organization_id, reference_number) WHERE reference_number IS NOT NULL;
CREATE INDEX ix_txn_search_trgm    ON fl.transactions
  USING gin ((coalesce(purpose,'') || ' ' || coalesce(received_from,'') || ' ' || coalesce(paid_to,'') || ' ' || coalesce(remarks,'')) gin_trgm_ops);

-- Guard rails enforced in the database in addition to the API:
--   * BR-017: no new transactions in non-ACTIVE funds
--   * a cancelled transaction is terminal (no edits, no un-cancel)
--   * immutable identity columns (org, fund, type, number, creator, client id)
CREATE OR REPLACE FUNCTION fl.guard_transactions() RETURNS trigger
  LANGUAGE plpgsql AS
$$
DECLARE v_fund_status fl.fund_status;
BEGIN
  IF TG_OP = 'INSERT' THEN
    SELECT status INTO v_fund_status FROM fl.funds WHERE id = NEW.fund_id;
    IF v_fund_status IS DISTINCT FROM 'ACTIVE' THEN
      RAISE EXCEPTION 'FUND_NOT_ACTIVE' USING ERRCODE = 'P0001';
    END IF;
    RETURN NEW;
  END IF;

  -- UPDATE
  IF OLD.status = 'CANCELLED' THEN
    RAISE EXCEPTION 'TXN_CANCELLED_IMMUTABLE' USING ERRCODE = 'P0001';
  END IF;
  IF NEW.organization_id <> OLD.organization_id OR NEW.fund_id <> OLD.fund_id
     OR NEW.txn_type <> OLD.txn_type OR NEW.txn_number <> OLD.txn_number
     OR NEW.created_by <> OLD.created_by OR NEW.created_at <> OLD.created_at
     OR NEW.client_txn_id IS DISTINCT FROM OLD.client_txn_id THEN
    RAISE EXCEPTION 'TXN_IMMUTABLE_FIELD' USING ERRCODE = 'P0001';
  END IF;
  SELECT status INTO v_fund_status FROM fl.funds WHERE id = NEW.fund_id;
  IF v_fund_status IS DISTINCT FROM 'ACTIVE' THEN
    RAISE EXCEPTION 'FUND_NOT_ACTIVE' USING ERRCODE = 'P0001';
  END IF;
  -- Every change (edit OR cancellation) is a new revision, so each has its own history entry.
  NEW.revision := OLD.revision + 1;
  NEW.updated_at := now();
  RETURN NEW;
END
$$;
CREATE TRIGGER trg_txn_guard
  BEFORE INSERT OR UPDATE ON fl.transactions
  FOR EACH ROW EXECUTE FUNCTION fl.guard_transactions();

-- Full snapshot history of every revision (who changed what, and why).
-- Written by the API in the same DB transaction as the change.
CREATE TABLE fl.transaction_revisions (
  id                 uuid PRIMARY KEY,
  organization_id    uuid        NOT NULL REFERENCES fl.organizations(id),
  transaction_id     uuid        NOT NULL REFERENCES fl.transactions(id),
  revision           integer     NOT NULL,
  snapshot           jsonb       NOT NULL,                   -- full row as it was AFTER this revision
  change_reason      varchar(300),                           -- mandatory for revision > 1 (API-enforced)
  changed_by         uuid        NOT NULL REFERENCES fl.users(id),
  changed_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_txn_revision UNIQUE (transaction_id, revision)
);

-- =============================================================================
-- 9. Attachments (metadata only — bytes live in private object storage)
-- =============================================================================
CREATE TABLE fl.transaction_attachments (
  id                 uuid PRIMARY KEY,
  organization_id    uuid         NOT NULL REFERENCES fl.organizations(id),
  transaction_id     uuid         NOT NULL REFERENCES fl.transactions(id),
  storage_key        varchar(300) NOT NULL UNIQUE,           -- org/{org}/fund/{fund}/txn/{txn}/{uuid}.{ext}
  original_filename  varchar(200) NOT NULL,
  content_type       varchar(100) NOT NULL,
  size_bytes         integer      NOT NULL CHECK (size_bytes > 0),
  sha256             char(64)     NOT NULL,
  uploaded_by        uuid         NOT NULL REFERENCES fl.users(id),
  uploaded_at        timestamptz  NOT NULL DEFAULT now(),
  is_hidden          boolean      NOT NULL DEFAULT false,    -- admin can hide; never hard-deleted
  hidden_by          uuid REFERENCES fl.users(id),
  hidden_reason      varchar(200)
);
CREATE INDEX ix_attach_txn ON fl.transaction_attachments (transaction_id);

-- =============================================================================
-- 10. Audit log — append-only (PRD §14)
-- =============================================================================
CREATE TABLE fl.audit_logs (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  organization_id    uuid         NOT NULL REFERENCES fl.organizations(id),
  user_id            uuid REFERENCES fl.users(id),           -- null for system / failed login of unknown number
  action             varchar(60)  NOT NULL,                  -- e.g. TXN_CREATED, USER_DEACTIVATED (see doc §6)
  entity_type        varchar(40)  NOT NULL,
  entity_id          varchar(64),
  fund_id            uuid REFERENCES fl.funds(id),
  old_value          jsonb,
  new_value          jsonb,
  reason             varchar(300),
  request_id         varchar(64),                            -- correlation id
  ip_address         inet,
  device_info        varchar(200),
  created_at         timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_org_created ON fl.audit_logs (organization_id, created_at DESC);
CREATE INDEX ix_audit_entity      ON fl.audit_logs (entity_type, entity_id);
CREATE INDEX ix_audit_user        ON fl.audit_logs (user_id, created_at DESC);

CREATE OR REPLACE FUNCTION fl.audit_append_only() RETURNS trigger
  LANGUAGE plpgsql AS
$$ BEGIN RAISE EXCEPTION 'AUDIT_LOG_APPEND_ONLY' USING ERRCODE = 'P0001'; END $$;
CREATE TRIGGER trg_audit_no_update BEFORE UPDATE OR DELETE ON fl.audit_logs
  FOR EACH ROW EXECUTE FUNCTION fl.audit_append_only();
CREATE TRIGGER trg_revisions_no_update BEFORE UPDATE OR DELETE ON fl.transaction_revisions
  FOR EACH ROW EXECUTE FUNCTION fl.audit_append_only();

-- =============================================================================
-- 11. Background export jobs (PRD §17.3; heavy work off the request path)
-- =============================================================================
CREATE TABLE fl.export_jobs (
  id                 uuid PRIMARY KEY,
  organization_id    uuid         NOT NULL REFERENCES fl.organizations(id),
  requested_by       uuid         NOT NULL REFERENCES fl.users(id),
  report_code        varchar(40)  NOT NULL,                  -- FUND_SUMMARY, DAILY, ... (doc §7)
  format             varchar(4)   NOT NULL CHECK (format IN ('XLSX','CSV','PDF')),
  parameters         jsonb        NOT NULL,                  -- fund, date range, filters (validated)
  idempotency_key    uuid         NOT NULL,
  status             fl.export_status NOT NULL DEFAULT 'QUEUED',
  storage_key        varchar(300),
  row_count          integer,
  error_code         varchar(60),
  created_at         timestamptz  NOT NULL DEFAULT now(),
  started_at         timestamptz,
  finished_at        timestamptz,
  expires_at         timestamptz,
  CONSTRAINT uq_export_idem UNIQUE (requested_by, idempotency_key)
);
CREATE INDEX ix_export_queue ON fl.export_jobs (status, created_at) WHERE status IN ('QUEUED','RUNNING');

-- =============================================================================
-- 12. Balance views (source of truth = transactions; nothing is stored)
-- Signed movement per (fund, account) for ACTIVE transactions only.
-- =============================================================================
CREATE OR REPLACE VIEW fl.v_account_movements WITH (security_invoker = true) AS
  SELECT t.organization_id, t.fund_id, t.account_id, t.txn_type, t.txn_date,
         t.amount AS signed_amount, t.created_by
    FROM fl.transactions t
   WHERE t.status = 'ACTIVE' AND t.txn_type = 'DEPOSIT'
  UNION ALL
  SELECT t.organization_id, t.fund_id, t.account_id, t.txn_type, t.txn_date,
         -t.amount, t.created_by
    FROM fl.transactions t
   WHERE t.status = 'ACTIVE' AND t.txn_type = 'EXPENSE'
  UNION ALL
  SELECT t.organization_id, t.fund_id, t.account_id, t.txn_type, t.txn_date,
         CASE t.adjustment_direction WHEN 'INCREASE' THEN t.amount ELSE -t.amount END, t.created_by
    FROM fl.transactions t
   WHERE t.status = 'ACTIVE' AND t.txn_type = 'ADJUSTMENT'
  UNION ALL
  SELECT t.organization_id, t.fund_id, t.from_account_id, t.txn_type, t.txn_date,
         -t.amount, t.created_by
    FROM fl.transactions t
   WHERE t.status = 'ACTIVE' AND t.txn_type = 'TRANSFER'
  UNION ALL
  SELECT t.organization_id, t.fund_id, t.to_account_id, t.txn_type, t.txn_date,
         t.amount, t.created_by
    FROM fl.transactions t
   WHERE t.status = 'ACTIVE' AND t.txn_type = 'TRANSFER';

-- Account Closing Balance = Opening + In - Out + TransfersIn - TransfersOut +/- Adj  (PRD §12.4)
CREATE OR REPLACE VIEW fl.v_fund_account_balances WITH (security_invoker = true) AS
  WITH pairs AS (
    SELECT organization_id, fund_id, account_id FROM fl.opening_balances
    UNION
    SELECT DISTINCT organization_id, fund_id, account_id FROM fl.v_account_movements
  )
  SELECT p.organization_id, p.fund_id, p.account_id,
         coalesce(ob.amount, 0)                                                        AS opening_balance,
         coalesce(sum(m.signed_amount) FILTER (WHERE m.txn_type = 'DEPOSIT'), 0)       AS money_in,
         coalesce(-sum(m.signed_amount) FILTER (WHERE m.txn_type = 'EXPENSE'), 0)      AS money_out,
         coalesce(sum(m.signed_amount) FILTER (WHERE m.txn_type = 'TRANSFER' AND m.signed_amount > 0), 0)  AS transfers_in,
         coalesce(-sum(m.signed_amount) FILTER (WHERE m.txn_type = 'TRANSFER' AND m.signed_amount < 0), 0) AS transfers_out,
         coalesce(sum(m.signed_amount) FILTER (WHERE m.txn_type = 'ADJUSTMENT'), 0)    AS adjustments_net,
         coalesce(ob.amount, 0) + coalesce(sum(m.signed_amount), 0)                    AS closing_balance
    FROM pairs p
    LEFT JOIN fl.opening_balances ob ON ob.fund_id = p.fund_id AND ob.account_id = p.account_id
    LEFT JOIN fl.v_account_movements m ON m.fund_id = p.fund_id AND m.account_id = p.account_id
   GROUP BY p.organization_id, p.fund_id, p.account_id, ob.amount;

-- Fund Closing Balance = Opening + In - Out +/- Adj; transfers net to zero (PRD §12.3, BR-011)
CREATE OR REPLACE VIEW fl.v_fund_balances WITH (security_invoker = true) AS
  SELECT organization_id, fund_id,
         sum(opening_balance)  AS opening_balance,
         sum(money_in)         AS money_in,
         sum(money_out)        AS money_out,
         sum(adjustments_net)  AS adjustments_net,
         sum(closing_balance)  AS closing_balance
    FROM fl.v_fund_account_balances
   GROUP BY organization_id, fund_id;

-- =============================================================================
-- 13. Row-Level Security
-- Layer 1 (all tenant tables): organization isolation.
-- Layer 2 (fund-scoped tables): members only see funds they are assigned to.
-- The API ALSO enforces these rules; RLS is defense in depth (Standard §2.4).
-- =============================================================================
CREATE OR REPLACE FUNCTION fl.has_fund_access(p_fund_id uuid) RETURNS boolean
  LANGUAGE sql STABLE AS
$$
  SELECT fl.current_is_admin()
      OR EXISTS (SELECT 1 FROM fl.user_fund_access a
                  WHERE a.user_id = fl.current_user_id() AND a.fund_id = p_fund_id)
$$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'settings','users','user_sessions','fund_types','payment_modes','funds','user_fund_access',
    'accounts','opening_balances','categories','txn_number_sequences','transactions',
    'transaction_revisions','transaction_attachments','audit_logs','export_jobs']
  LOOP
    EXECUTE format('ALTER TABLE fl.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE fl.%I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format($p$CREATE POLICY tenant_isolation ON fl.%I
                      USING (organization_id = fl.current_org_id())
                      WITH CHECK (organization_id = fl.current_org_id())$p$, t);
  END LOOP;
END $$;

ALTER TABLE fl.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE fl.organizations FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_self ON fl.organizations
  USING (id = fl.current_org_id()) WITH CHECK (id = fl.current_org_id());

-- Fund-level restriction (restrictive = AND-ed with tenant_isolation)
CREATE POLICY fund_access ON fl.funds AS RESTRICTIVE
  USING (fl.has_fund_access(id));
CREATE POLICY fund_access ON fl.transactions AS RESTRICTIVE
  USING (fl.has_fund_access(fund_id));
CREATE POLICY fund_access ON fl.transaction_revisions AS RESTRICTIVE
  USING (fl.current_is_admin() OR EXISTS (
          SELECT 1 FROM fl.transactions t WHERE t.id = transaction_id));
CREATE POLICY fund_access ON fl.transaction_attachments AS RESTRICTIVE
  USING (EXISTS (SELECT 1 FROM fl.transactions t WHERE t.id = transaction_id));
CREATE POLICY fund_access ON fl.opening_balances AS RESTRICTIVE
  USING (fl.has_fund_access(fund_id));

-- Audit logs: only admins can read; anyone authenticated in the tenant can append.
CREATE POLICY audit_admin_read ON fl.audit_logs AS RESTRICTIVE FOR SELECT
  USING (fl.current_is_admin());

-- Pre-authentication lookups (PIN login, refresh) run through narrowly
-- scoped SECURITY DEFINER functions instead of disabling RLS for the app role.
CREATE OR REPLACE FUNCTION fl.auth_find_user_by_mobile(p_mobile varchar)
  RETURNS TABLE (user_id uuid, organization_id uuid, role fl.user_role, status fl.user_status,
                 pin_hash text, pin_set_at timestamptz, pin_must_change boolean)
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = fl, pg_temp AS
$$
  SELECT u.id, u.organization_id, u.role, u.status, u.pin_hash, u.pin_set_at, u.pin_must_change
    FROM fl.users u JOIN fl.organizations o ON o.id = u.organization_id
   WHERE u.mobile_e164 = p_mobile AND o.is_active
$$;

CREATE OR REPLACE FUNCTION fl.auth_find_session(p_hash bytea)
  RETURNS SETOF fl.user_sessions
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = fl, pg_temp AS
$$ SELECT * FROM fl.user_sessions WHERE refresh_token_hash = p_hash $$;

GRANT USAGE ON SCHEMA fl TO fundledger_auth_definer;
GRANT SELECT ON fl.users, fl.organizations, fl.user_sessions TO fundledger_auth_definer;
-- PG16+: transferring ownership requires the current role to be able to SET ROLE
-- to the new owner (managed hosts like Neon do not run migrations as superuser).
-- The new owner also needs CREATE on the schema at transfer time.
-- Grant both temporarily, transfer, then revoke so no login role keeps the path.
-- Pre-auth functions return PIN hashes: only the API role may execute them.
REVOKE EXECUTE ON FUNCTION fl.auth_find_user_by_mobile(varchar), fl.auth_find_session(bytea) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION fl.auth_find_user_by_mobile(varchar), fl.auth_find_session(bytea) TO fundledger_app;
GRANT fundledger_auth_definer TO CURRENT_USER;
GRANT CREATE ON SCHEMA fl TO fundledger_auth_definer;
ALTER FUNCTION fl.auth_find_user_by_mobile(varchar) OWNER TO fundledger_auth_definer;
ALTER FUNCTION fl.auth_find_session(bytea)          OWNER TO fundledger_auth_definer;
REVOKE CREATE ON SCHEMA fl FROM fundledger_auth_definer;
REVOKE fundledger_auth_definer FROM CURRENT_USER;

-- =============================================================================
-- 14. Grants (least privilege, PRD §22 / Standard §2.5)
-- =============================================================================
GRANT USAGE ON SCHEMA fl TO fundledger_app, fundledger_readonly;

GRANT SELECT ON ALL TABLES IN SCHEMA fl TO fundledger_readonly;

GRANT SELECT, INSERT, UPDATE ON
  fl.organizations, fl.settings, fl.users, fl.user_sessions, fl.fund_types, fl.payment_modes,
  fl.funds, fl.accounts, fl.opening_balances, fl.categories, fl.txn_number_sequences,
  fl.transactions, fl.transaction_attachments, fl.export_jobs
  TO fundledger_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON fl.user_fund_access TO fundledger_app;   -- access rows are revocable
GRANT SELECT, INSERT ON fl.audit_logs, fl.transaction_revisions TO fundledger_app;
GRANT SELECT, INSERT ON fl.login_attempts TO fundledger_app;                      -- no tenant (pre-auth)
GRANT SELECT ON fl.v_account_movements, fl.v_fund_account_balances, fl.v_fund_balances
  TO fundledger_app, fundledger_readonly;
-- Grant EXECUTE on the functions this role owns. (A blanket "ON ALL FUNCTIONS" grant
-- FAILS on non-superuser hosts such as Neon: the auth_* functions belong to
-- fundledger_auth_definer and PUBLIC no longer has EXECUTE on them; they were granted
-- explicitly in section 13.)
DO $$
DECLARE f regprocedure;
BEGIN
  FOR f IN SELECT p.oid::regprocedure FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
            WHERE n.nspname = 'fl' AND p.proowner = (SELECT oid FROM pg_roles WHERE rolname = current_user)
  LOOP
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO fundledger_app', f);
  END LOOP;
END $$;
-- NOTE: no DELETE on transactions, audit_logs, revisions, attachments (BR-012).

COMMIT;
